version: '3.3'

services:

  db:
    image: mysql:5.6
    volumes:
      - ./data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: default
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    network_mode: bridge
    ports:
      - "3306:3306"
    expose:
      - "3306"